version: '3.8'

services:
  documind:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: documind-app
    ports:
      - "8000:8000"
      - "7860:7860"
    volumes:
      - .:/app
    env_file:
      - .env
