version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: documind-backend
    ports:
      - "8000:8000"
    
    volumes:
      - .:/app
    
    env_file:
      - .env