from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

# --- Request Schema (Data coming IN to our API) ---

class QueryRequest(BaseModel):
    """
    Schema for the incoming user question.
    """
    # The '...' means this field is strictly required.
    query: str = Field(..., description="The user's question to ask the RAG system.", min_length=1)


# --- Response Schemas  ---

class DocumentSource(BaseModel):
    """
    Schema for a single retrieved document chunk used as a source.
    """
    page_content: str = Field(..., description="The actual text content of the retrieved chunk.")
    # Metadata is a dictionary that might contain 'source' (filename), 'page', etc.
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata associated with the document chunk.")

class QueryResponse(BaseModel):
    """
    Schema for the final response returned to the user.
    """
    answer: str = Field(..., description="The final answer generated by the Groq LLM.")
    sources: List[DocumentSource] = Field(default_factory=list, description="The list of document chunks used as context.")